service: doggo-directory
app: doggo-directory
org: technotone

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: 
        - { "Fn::GetAtt": ["DirectoryTable", "Arn"]}

functions:
  createDog:
    handler: src/handlers.createDog
    events:
      - httpApi:
          path: /
          method: post
  getDog:
    handler: src/handlers.getDog
    events: 
      - httpApi:
          path: /dog/{id}
          method: get
  updateDog:
    handler: src/handlers.updateDog
    events: 
    - httpApi:
        path: /dog/{id}
        method: put
  deleteDog:
    handler: src/handlers.deleteDog
    events: 
    - httpApi:
        path: /dog/{id}
        method: delete
  getAllDogs:
    handler: src/handlers.getAllDogs
    events: 
    - httpApi:
        path: /dogs
        method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    DirectoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DirectoryTable
        AttributeDefinitions:
          - AttributeName: dogID
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: dogID
            KeyType: HASH